### ISSUE TITLE
Completed module 1 assignments

### ISSUE THREAD

**Issue by PatriciaTendai** [ds4owd-001/md-02-assignments-PatriciaTendai#1]
@larnsce , @mianzg , @sskorik01

**Comment by larnsce** [comment]
Thank you for tagging us @PatriciaTendai, the title of the issue says "module 1" but I assume you mean "module 2". 

You opened an issue, but I do not see any changes that were committed and pushed to GitHub. Could you check if you have worked through these steps? https://ds4owd-001.github.io/website/assignments/md-02/am-02-1-data-visualisation.html#step-2-commit-and-push-your-changes

**Comment by PatriciaTendai** [comment]
> Thank you for tagging us @PatriciaTendai, the title of the issue says "module 1" but I assume you mean "module 2".
> 
> You opened an issue, but I do not see any changes that were committed and pushed to GitHub. Could you check if you have worked through these steps? https://ds4owd-001.github.io/website/assignments/md-02/am-02-1-data-visualisation.html#step-2-commit-and-push-your-changes

hi Larz, my apologies I got lost. am catching up now, I have revised assignment 2. 
I think I also have issues pushing my assignment to github. I have committed and issued assignment 3, but I can't find it under the issues tab

**Comment by larnsce** [comment]
Great job @PatriciaTendai! You can see a comparison of what was deleted/edited (red - left side) and was added (green - right side) here: https://github.com/ds4owd-001/md-02-assignments-PatriciaTendai/commit/a7ef4a732a97e45c0e46f68e6a4dafb524fa38b8

I will close the issue for you now
